@startuml

skinparam monochrome true


partition Setup {
    (*) --> "Search for pair"
}

partition Activity {
"Search for pair" --> Loop

If "slfjojwof"
-->[Yes] "Press button"
--> "accrue activity"
--> === S1 ===
else
--> "lights off"
Endif

--> === S1 ===
}

partition Sync {
=== S1 === --> "Time Tremor"
}

@enduml
