@startuml

skinparam monochrome true


partition Setup {
(*) --> "Search for pair"
--> if "" then
--> [Found] === A1 ===
else
-->[Not Found] "Search for pair"
endif

}

partition Activity {
=== A1 === --> Loop

If "slfjojwof"
-->[Yes] "Press button"
--> "accrue activity"
--> === S1 ===
else
--> "lights off"
Endif

--> === S1 ===

Loop if "" then 
--> "Heart Rate"
else
--> "No Heart Rate"
endif
--> === S1 ===



}

partition Sync {
=== S1 === --> "Time Tremor"
--> Loop
}

@enduml
